package errors

import "errors"

var (
	// Custom Error
	ErrCantResetPassword              = errors.New("can not reset password for this account")
	ErrDuplicateKey                   = errors.New("duplicate key")
	ErrDataNotFound                   = errors.New("data not found")
	ErrForbidden                      = errors.New("you don't have permission to access")
	ErrWrongAuthMethod                = errors.New("wrong login method")
	ErrWrongLoginCredential           = errors.New("wrong email or password")
	ErrWrongOldPassword               = errors.New("incorrect old password")
	ErrFailedParseEmailTemplate       = errors.New("failed parse email template")
	ErrFailedSendEmail                = errors.New("failed send email")
	ErrNameAlreadyExists              = errors.New("name already exist")
	ErrUsernameAlreadyExists          = errors.New("username already exist")
	ErrEmailAlreadyExists             = errors.New("email already exist")
	ErrPhoneNumberAlreadyExists       = errors.New("phone number already exist")
	ErrEmailNotRegistered             = errors.New("email is not registered")
	ErrEmailAlreadyVerified           = errors.New("email is already verified")
	ErrUserIsNotActivated             = errors.New("user is not activated")
	ErrConfirmPasswordNotSame         = errors.New("password and confirm password are not same")
	ErrInvalidVerificationCode        = errors.New("invalid verification code")
	ErrEventNotRunning                = errors.New("event is not running")
	ErrLatestEventRunning             = errors.New("another event is running")
	ErrUnsupportedFileFormat          = errors.New("file format is not supported")
	ErrWrongFileUploadPath            = errors.New("wrong file upload path")
	ErrHaveUnprocessedPayment         = errors.New("can not create payment due to you have unprocessed payment")
	ErrInvoiceIsPaid                  = errors.New("can not create payment due to your payment's status is paid")
	ErrHasTeam                        = errors.New("participant already has a team")
	ErrNotCompleteProfile             = errors.New("participant's profile is not completely filled")
	ErrPaymentNotPaid                 = errors.New("payment status is not paid")
	ErrEventMentorExist               = errors.New("event mentor already exist")
	ErrEventJudgeExist                = errors.New("event judge already exist")
	ErrRegistrationNotCompleted       = errors.New("registration is not completed, please check again")
	ErrTeamNameAlreadyExists          = errors.New("team name already exist")
	ErrTeamCodeAlreadyExists          = errors.New("team code already exist")
	ErrScheduleDateNotValid           = errors.New("schedule date is not valid")
	ErrParticipantHasBeenInvited      = errors.New("participant has been invited by this team")
	ErrInvitationHasBeenProceed       = errors.New("invitation has been proceed")
	ErrTeamReqHasBeenProceed          = errors.New("the request has been proceed")
	ErrTeamIsFull                     = errors.New("the number of team members reached the limit")
	ErrCannotRemoveTeamAdmin          = errors.New("can not remove team's admin")
	ErrParticipantRequestedToJoinTeam = errors.New("participant already sent a request to join the team")
	ErrCannotRequestToJoinYourTeam    = errors.New("can not send request to join your own team")
	ErrTeamAlreadyHasProject          = errors.New("team already has a project")
	ErrProjectStatusShouldBeDraft     = errors.New("project's status should be draft")
	ErrProjectStatusShouldBeSubmitted = errors.New("project's status should be submitted")
	ErrInvalidStatus                  = errors.New("invalid status")
)
